# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4431eb909c0e6549d39d3858c1f8796e58ace7b9db94cd8c3c41dc63b8596f0d7b391143bcbfd12db64975f997c05460a9125afa9e41d7d653617fb92fb9f21a

test:
  secret_key_base: 92f36c746998ffe0a66f684c38e0d86f3ac895e436c71c5c1f1bab03be3cd9784d41428bdb356d2d4c48f1ef186e0d9660a1aa1d68b1076a1fd6d0d47afca995

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
